// PLACEHOLDER — generated stand-in until `flutterfire configure` runs.
//
// This file is normally auto-generated by the FlutterFire CLI
// (`flutterfire configure`) once a real Firebase project exists. It is
// checked in here only so the project compiles/tests locally before that
// step happens; running `flutterfire configure` will overwrite it with real
// values pointing at the actual Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android in this '
          'project. Run `flutterfire configure` to add another platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mT48V_Q4P6R21JS4YcPkfJEFUeo4B9Y',
    appId: '1:963651852002:android:b7da4e477f1ec934f1f0bb',
    messagingSenderId: '963651852002',
    projectId: 'greyvetro-budget-tracker',
    storageBucket: 'greyvetro-budget-tracker.firebasestorage.app',
  );
}
