// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tZfWncJhkhV6NFMsqTO1EDH3BWkNNQU',
    appId: '1:963651852002:web:8bd65072a5c50f6ef1f0bb',
    messagingSenderId: '963651852002',
    projectId: 'greyvetro-budget-tracker',
    authDomain: 'greyvetro-budget-tracker.firebaseapp.com',
    storageBucket: 'greyvetro-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mT48V_Q4P6R21JS4YcPkfJEFUeo4B9Y',
    appId: '1:963651852002:android:b7da4e477f1ec934f1f0bb',
    messagingSenderId: '963651852002',
    projectId: 'greyvetro-budget-tracker',
    storageBucket: 'greyvetro-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvBx7FlPmf6enFT7dokmyz8Pr2fnpHo4',
    appId: '1:963651852002:ios:e5704e112a926efbf1f0bb',
    messagingSenderId: '963651852002',
    projectId: 'greyvetro-budget-tracker',
    storageBucket: 'greyvetro-budget-tracker.firebasestorage.app',
    androidClientId: '963651852002-gavfdaagr67muvhs3fo6esqqjg4sij00.apps.googleusercontent.com',
    iosClientId: '963651852002-84ak7pk40f3md0fqnms2lr2qmsntkfa0.apps.googleusercontent.com',
    iosBundleId: 'com.greyvetro.greyvetroBudgetTracker',
  );
}
